# <span style='color:blue'> <u>PyTorch</u> <i> (ML framework based on Torch Library, used for CV & NLP)</i> </span>

## <span style='color:green'> Top Deep Learning Frameworks</span>
1. **TensorFlow** by Google Brain (Python,Cpp,R) Eg. Google Translate
2. **Keras** (minimalist, part of TensorFlow core API)
3. **mxnet** (Python,Cpp,R,Julia,Scala)
4. **PyTorch** by Facebook (Python)
5. **Caffe** (C, C++, Python, MATLAB, Command Line), high speed Eg.Vision Recognition
6. **Microsoft Cognitive Toolkit(CNTK)** (Python, Cpp, Commandline) Eg.Image, handwriting & Speech Recognition
7. **DL4J** Deep Learning for Java (JVM lang - Java, Scala, Clojure, Kotlin) Eg. Image recog, fraud detect, Text-mining, NLP
8. **ONNX** Open Neural Network Exchange, by Microsoft & FB
9. **MATLAB – Deep Learning Toolbox** (c,cpp,Java, MATLAB)


### **Tensor of Order 1  --  Vector**
### **Tensor of Order 2  --  Matrix**
### **Tensor of Order 3  --  Box/Cube**
### **Tensor of Order n  --  Hyperbox\Hypercube**

In [3]:
import numpy as np
import torch
import matplotlib.pyplot as plt

In [6]:
x = torch.rand(4, 3)
print(x)

tensor([[0.9924, 0.7195, 0.4345],
        [0.3353, 0.7922, 0.0850],
        [0.4383, 0.6837, 0.8198],
        [0.9175, 0.0901, 0.6725]])


In [18]:
# Use of PyTorch Tensors to fit a third order polynomial to sine function

import torch
import math

dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# Create random input and output data
x = torch.linspace(-math.pi, math.pi, 2000, device=device, dtype=dtype)
y = torch.sin(x)

# Randomly initialize weights
a = torch.randn((), device=device, dtype=dtype)
b = torch.randn((), device=device, dtype=dtype)
c = torch.randn((), device=device, dtype=dtype)
d = torch.randn((), device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(2000):
    # Forward pass: compute predicted y
    y_pred = a + b * x + c * x ** 2 + d * x ** 3

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
   # if t % 100 == 99:
        #print(t, loss)

    # Backprop to compute gradients of a, b, c, d with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_a = grad_y_pred.sum()
    grad_b = (grad_y_pred * x).sum()
    grad_c = (grad_y_pred * x ** 2).sum()
    grad_d = (grad_y_pred * x ** 3).sum()

    # Update weights using gradient descent
    a -= learning_rate * grad_a
    b -= learning_rate * grad_b
    c -= learning_rate * grad_c
    d -= learning_rate * grad_d


print(f'Result: y = {a.item()} + {b.item()} X + {c.item()} X^2 + {d.item()} X^3')


Result: y = -0.0018277362687513232 + 0.8629119396209717 X + 0.0003153153520543128 X^2 + -0.09420817345380783 X^3


In [35]:
# Reshaping a Tensor
import numpy as np
import torch
import matplotlib.pyplot as plt

x=torch.randn(2,3)
print(x)
print(x.view(1,6)) 

print(x.size())

# Methods that mutate tensor has an underscore suffix
x.add_(torch.ones(2,3)) 
print(x)

tensor([[ 0.7494, -0.7915, -1.4652],
        [-1.4576, -1.7870, -0.4322]])
tensor([[ 0.7494, -0.7915, -1.4652, -1.4576, -1.7870, -0.4322]])
torch.Size([2, 3])
tensor([[ 1.7494,  0.2085, -0.4652],
        [-0.4576, -0.7870,  0.5678]])


In [36]:
torch.FloatTensor.abs(x)  # Doesn not modify x, but computes in anew tensor

tensor([[1.7494, 0.2085, 0.4652],
        [0.4576, 0.7870, 0.5678]])

In [37]:
print(x)
torch.FloatTensor.abs_(x)  # modifies x in place

tensor([[ 1.7494,  0.2085, -0.4652],
        [-0.4576, -0.7870,  0.5678]])


tensor([[1.7494, 0.2085, 0.4652],
        [0.4576, 0.7870, 0.5678]])

 ### <span style='color:blue'> Indexing & Slicing of Tensor Elements </span>

In [40]:
x = torch.tensor([[1,2,3],[4,5,6]])
x[0][1], x[0][2], x[1][0]

(tensor(2), tensor(3), tensor(4))

In [41]:
x[0], x[:,1]

(tensor([1, 2, 3]), tensor([2, 5]))

In [43]:
x = torch.tensor(4)
x.item()    # To get data from a single value tensor

4

In [51]:
# Changing Data type
x = torch.randn(2,2)    # Initially dtype = float32 (default), device = cpu
print(x)
print(x.to(torch.float64))     # changing data type

tensor([[1.5031, 0.6730],
        [1.1890, 1.8791]])
tensor([[1.5031, 0.6730],
        [1.1890, 1.8791]], dtype=torch.float64)


In [61]:
if torch.cuda.is_available():
    x=10*x.cuda()
    print("cuda yes")
else:
    print("cuda no")
x.cpu()


cuda no


tensor([[1.5031, 0.6730],
        [1.1890, 1.8791]])

In [63]:
# NumPy Array to Torch tensor and Vice versa
a = np.random.rand(5,3)
b = torch.Tensor(a)   #---torch
print(b)
a = b.numpy()
print(a)  #---numpy
print(b.size())
print(b.shape)
print(a.shape)

tensor([[0.9619, 0.4541, 0.2652],
        [0.6046, 0.6109, 0.2612],
        [0.7941, 0.0466, 0.0825],
        [0.3111, 0.1079, 0.7761],
        [0.6029, 0.8659, 0.3349]])
[[0.9619485  0.45410228 0.26516333]
 [0.60457665 0.61087847 0.26118985]
 [0.794105   0.04655844 0.08250754]
 [0.31105056 0.10793324 0.77607375]
 [0.60292536 0.86588484 0.33486098]]
torch.Size([5, 3])
torch.Size([5, 3])
(5, 3)


In [65]:
c = torch.randn(3,5)
mul = b@c
print(mul)

tensor([[ 0.7197, -1.4941, -0.0624,  0.9473, -0.8516],
        [ 0.6845, -1.6176,  0.1721,  0.8909, -0.5531],
        [ 0.3969, -0.5766, -0.2931,  0.4670, -0.6137],
        [-0.4259,  0.0709,  0.4404,  0.5602, -1.4928],
        [ 0.8659, -2.1484,  0.3382,  1.1214, -0.5654]])


In [68]:
x= torch.ones(5,1,2,1,4)  # creates a 5-D tensor
print(x)
x.size()

tensor([[[[[1., 1., 1., 1.]],

          [[1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.]],

          [[1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.]],

          [[1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.]],

          [[1., 1., 1., 1.]]]],



        [[[[1., 1., 1., 1.]],

          [[1., 1., 1., 1.]]]]])


torch.Size([5, 1, 2, 1, 4])

In [69]:
y = torch.squeeze(x) # Squeezes out Dimesions of just size 1
print(y)
y.size()

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]])


torch.Size([5, 2, 4])

In [70]:
y = torch.squeeze(x,3)  # Removes the 3rd Dimension
y.size()

torch.Size([5, 1, 2, 4])

In [71]:
z = torch.unsqueeze(y,3)  # Inserts a Dimension of 1 at the 3-rd index
z.size()

torch.Size([5, 1, 2, 1, 4])

In [72]:
# Checking for Element-wise Equality
a = torch.Tensor([1,2,3,1])
b = torch.ones(4)
torch.eq(a,b)

tensor([ True, False, False,  True])

In [82]:
a = torch.tensor([1,2,3,4])
print(a)
b = torch.randn(4)
print(b)
b.type_as(a)   # Match data type of Tensor to that of another tensor

tensor([1, 2, 3, 4])
tensor([ 1.5896, -0.6798,  0.1966, -0.2924])


tensor([1, 0, 0, 0])